netlify/netlify-identity-widget

src/state/store.js
Mainly to make the linter happy, but also because these are errors, I think we should display them as errors.
=> console.error instead of log

src/components/modal.css
While testing out the identity widget I noticed that the *or* is not actually showing. 
My feeling is that it is implied, so I removed it in this PR.
=> removes the relative or

package.json, src/netlify-identity.js, webpack.config.babel.js
This allows the widget to be used with netlify's role based access control
=> Set a cookie when not using cors

src/components/app.js, src/state/store.js
If a consumer calls logout without a user, the widget becomes stuck in the saving state.  This clears it.
=> Clear saving state when logout is called without a user

package.json, yarn.lock
Should fix a race condition when several places calls `user.jwt()` at the same time in apps consuming the widget.
=> Update gotrue and bump the widget version

README.md, example/src/index.js, src/components/app.js, src/netlify-identity.js, src/state/store.js
Add option to allow the definition of an APIUrl for when you want to use a absolute URL from a Cordova app or electron app.
=> Add APIUrl option to module API

src/netlify-identity.js
It seems adblock pro started setting `display: none` on all iframes with `src="about:blank"` :/
This is a quick fix for the identity widget
=> Fix adblock pro blocking

webpack.umd.config.babel.js
We had hidden source maps preventing devtools from picking up sourcemaps.
=> Fix source maps on UMD

src/netlify-identity.js
This guards against an observed scenario where netlify-cms (and other SPA's using hash routing) might insert a `\` into the hash on page load.
=> Improve hash cleaning regex

src/components/forms/siteurl.js
This seems to cause quite a bit of confusion for some people on whether to enter their local server URL or the live Netlify site URL. This wording might need to be changed a bit, though, any thoughts?
> @rafaelconde from https://github.com/netlify/netlify-identity-widget/pull/31:
> Maybe add a documentation link somewhere? I am still not sure, but it would be nice to give some guidance to people who have no idea what it might mean, your Netlify site URL.
Related to #40.
=> Clarify local Site URL popup.

src/components/modal.css
Alternate option for #121 
Making the `X` in the widget close button a bit bigger and centered with the hover circular outline.
The reason I opted to keep `x` as opposed to `✕` is to make it more balanced with the rest of the typography.
=> Make Close Button bigger and centered

src/index.js
Fixes widget not initializing if loaded async or after the `DOMContentLoaded` event fires. That event fires when `readystate` changes from initial state `loading` to `interactive`, so we should only use the listener if the current state is `loading`.
Reference: https://github.com/AustinGreen/gatsby-starter-netlify-cms/issues/55#issuecomment-370480787
=> Support async loading

src/components/app.js, src/components/forms/providers.js
*I am currently hired by Netlify to develop SAML 2.0 support in GoTrue. See this PR for the backend implementation: https://github.com/netlify/gotrue/pull/181*
There is going to be a `external.saml` key in the GoTrue `/settings` route.
This PR is used to add support for redirecting to this provider.
The SAML provider will behave exactly like any other provider in terms of frontend code. A redirect is issued to `/authorize?provider=saml` and the site receives a redirect with either a token or an error.
Also, this PR adds support to override the name of the provider which is used in the button of the widget. GoTrue will add a new key `external_labels` which contains these overrides. For the time being overrides will only be available for the SAML provider.
Example of the updated `/settings` …
=> Allow display of SAML provider button

RELEASE.md, package.json, src/components/app.js, yarn.lock
Add a few semver updates and implement a scripted release.
=> Semver updates and release tweaks

src/components/app.js, src/components/forms/siteurl.js, src/components/modal.css, src/netlify-identity.js, src/state/store.js
Currently, there is no way to switch out a localhost URL in a development version of Netlify Identity. 
Once a localhost URL has been added, you have to clear cookies in order to get a fresh Netlify Identity widget instance which would allow you to update a localhost URL.
This solution adds a development settings portion to the widget so a user can clear a localhost URL easily when working with different instances of Identity.
=> chore: Add feature to switch out identity url

src/components/app.js, src/netlify-identity.js, src/state/store.js
Problem: Development settings for identity that would allow adding and removing an identity URL were visible on production.
This fix checks the environment and makes sure that dev settings are only visible in dev mode.
=> fix: ensure dev settings for url is only visible on dev

README.md, src/netlify-identity.js
This fixes https://github.com/netlify/netlify-identity-widget/issues/233 by adding a `.refresh()` method to netlify-identity-widget that is the equivalent of running `netlifyIdentity.gotrue.currentUser().jwt()` . This PR also includes an update to the README. 
cc @jlengstorf
=> added refresh method from gotrue

CONTRIBUTING.md
`yarn start` doesn't exist.
Also fix a spelling mistake.
=> `yarn dev` is used to run the development server

package.json, yarn.lock
Updated `gotrue-js` per the new release, tested on the preview branch - seems good
=> chore: update gotrue-js

src/components/app.js, src/components/forms/user.js
This helps password managers (once #161 is fixed) along with accessibility tools.
=> Indicate via @autocomplete whether a password field is for new/current values

src/components/forms/user.js
Form type was set to email so the form placeholder asked for email when it needed name.
Before:
After:
closes #285
=> Changes Sign Up form type to name instead of email

README.md, src/netlify-identity.js, src/netlify-identity.test.js
Refactor callback management to use `Map` so that we can unregister
handlers without changing the current behavior.
=> feat: add support for unregistering event handlers

.prettierrc.js, src/netlify-identity.js, src/netlify-identity.test.js
(NOTE: don’t merge this until #283 goes in)
when setting the URL, the initialize function needs to be called or else the widget gets stuck. however, when no change is required, the init function was being called twice anyways, which caused some undesirable behavior
this adds a check to fix that
=> fix: prevent double initialization

package.json, yarn.lock
Related to https://github.com/netlify/netlify-identity-widget/pull/300
Could not find a place we're using this dependency.
Searched using `grep -rni --exclude-dir={node_modules,build} "raw-loader" .`
=> chore(deps): remove unused raw-loader dependency

src/components/app.js, src/components/modal/index.js
This PR adds the ability to clear an invalid site URL.
While I was going through the [RedwoodJS authentication tutorial](https://redwoodjs.com/tutorial/authentication) I had accidentally entered the wrong Netlify URL. It took me a hot minute to realize I had to remove it from my local storage. I figured it would be nice to have the "Clear localhost URL" button available if this error occurs.
Here's a gif of it in action!
=> feat: Add the ability to clear an invalid site URL

src/components/modal.css
on iOS, inputs with font sizes below 16px are automatically zoomed in, which causes issues with page layouts and hides the close button for the widget modal. this change increases the input size to 16px to avoid the zoom on mobile devices
fix #236
=> fix: increase input size to avoid mobile zoom

src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/hu.json
=> fix: add missing translations

README.md
Object has missing comma, which is located in comments instead
=> fix: module example code typo

src/components/forms/siteurl.js
When copy pasting the Identity URL from the Netlify Identity tab in the UI, it contains the `/.netlify/identity` path, while the widget expects it without the path.
This PR trims `https://<site-domain>/.netlify/identity` to `https://<site-domain>.netlify.app` to handle that use case.
=> fix: remove identity prefix from site URL if exists
