netlify/netlify-identity-widget

.travis.yml, README.md, package.json
Will enable travis when merged.
=> Enable travis

yarn.lock
=> Upgrade gotrue-js

src/components/app.js
=> Enable providers on accept invite page

src/index.ejs
Closes https://github.com/netlify/netlify-identity-widget/issues/57
=> Add links/badges to demo site

src/state/store.js
Closes https://github.com/netlify/netlify-identity-widget/issues/47
=> Don’t kick off loading state when linking to providers

.travis.yml
This makes travis also build the bundle when running linting and eventually tests.
=> Also make sure we can still build.

.npmignore, CHANGELOG.md, RELEASE.md, package.json, script/release.js, yarn.lock
A draft release process proposal.
=> Draft release doc

README.md
per #68, I feel there should be a mention of how local testing works
=> add FAQ to readme

src/state/store.js
Alternative approach since the last attempt didn't work
=> Dont start action unless there is a user

src/netlify-identity.js
This PR fix #94 by adding `z-index: 99` to the iframe style.
=> Add z-index to the iframe and fix #94

README.md, src/netlify-identity.js
Allow for `netlifyIdentity.open('signup')`
=> Add signup button action to public api

src/components/forms/user.js
Fix https://github.com/netlify/netlify-identity-widget/issues/140
=> update icon on name field

README.md
=> Fix small copy/paste error

README.md
Follow up of #153 
Silly me, the same error was repeated a few lines below.
=> fix small copy/paste error (again)

package.json
Looks like a dev dependency snuck into our dependencies.
=> Remove devDep from deps and fix release flow

README.md, src/components/app.js, src/components/forms/user.js, src/netlify-identity.js, src/state/store.js
#143 
add name placeholder customization
updated Readme.md
=> Added custom placeholder option

example/svelte/README.md
I made a Svelte demo based on the React and Vue examples. I added a README to the examples folder linking to my example. Hope it looks alright!
Thanks!
=> Add an example in Svelte

src/netlify-identity.js
Fixes https://github.com/netlify/netlify-cms/issues/1824
See comment here https://github.com/netlify/netlify-cms/issues/1824#issuecomment-559064466
Dependant on https://github.com/netlify/netlify-cms/pull/2920 to work
=> fix: don't open modal when using implicit auth from cms

webpack.umd.config.babel.js
fixes error with webpack umd output. see issue #318
=> fix: ReferenceError: window is not defined

renovate.json
Add a label in order to pass the test for required labels.
=> chore(renovate): add pr labels
